\set ON_ERROR_STOP on
\encoding UTF8

-- M2 core schema draft.
-- Internal primary keys use BIGINT identity for index locality.
-- Internal foreign keys use <entity>_id.
-- Public stable ids use public_id. API route names may still use resource names
-- such as {page_id}, but database schema stores those values in public_id.

CREATE OR REPLACE FUNCTION set_updated_at()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
BEGIN
    NEW.updated_at = now();
    RETURN NEW;
END;
$$;

CREATE OR REPLACE FUNCTION prevent_audit_logs_mutation()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
BEGIN
    RAISE EXCEPTION 'audit_logs is append-only and cannot be %', TG_OP;
END;
$$;

CREATE TABLE IF NOT EXISTS projects (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    name TEXT NOT NULL,
    description TEXT,
    schema_version TEXT NOT NULL DEFAULT 'v1',
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT pk_projects PRIMARY KEY (id),
    CONSTRAINT ck_projects_name_not_blank CHECK (btrim(name) <> ''),
    CONSTRAINT ck_projects_schema_version_not_blank CHECK (btrim(schema_version) <> '')
);

CREATE TABLE IF NOT EXISTS users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    username TEXT NOT NULL,
    email TEXT,
    display_name TEXT NOT NULL,
    password_hash TEXT,
    status TEXT NOT NULL DEFAULT 'pending',
    is_system_admin BOOLEAN NOT NULL DEFAULT false,
    last_login_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    deleted_at TIMESTAMPTZ,
    CONSTRAINT pk_users PRIMARY KEY (id),
    CONSTRAINT uq_users_username UNIQUE (username),
    CONSTRAINT ck_users_username_not_blank CHECK (btrim(username) <> ''),
    CONSTRAINT ck_users_display_name_not_blank CHECK (btrim(display_name) <> ''),
    CONSTRAINT ck_users_status CHECK (status IN ('active', 'disabled', 'pending'))
);

CREATE UNIQUE INDEX IF NOT EXISTS uq_users_email
    ON users (email)
    WHERE email IS NOT NULL;

ALTER TABLE projects
    ADD COLUMN IF NOT EXISTS created_by BIGINT;

ALTER TABLE projects
    ALTER COLUMN created_by SET NOT NULL;

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM pg_constraint
        WHERE conname = 'fk_projects_created_by'
    ) THEN
        ALTER TABLE projects
            ADD CONSTRAINT fk_projects_created_by
            FOREIGN KEY (created_by) REFERENCES users (id);
    END IF;
END;
$$;

COMMENT ON COLUMN projects.created_by IS '创建者用户 ID。';

CREATE TABLE IF NOT EXISTS role_registry (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    code TEXT NOT NULL,
    display_name TEXT NOT NULL,
    scope TEXT NOT NULL,
    description TEXT,
    permissions_json JSONB NOT NULL DEFAULT '{}'::jsonb,
    is_builtin BOOLEAN NOT NULL DEFAULT true,
    is_active BOOLEAN NOT NULL DEFAULT true,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT pk_role_registry PRIMARY KEY (id),
    CONSTRAINT uq_role_registry_code UNIQUE (code),
    CONSTRAINT uq_role_registry_id_scope UNIQUE (id, scope),
    CONSTRAINT ck_role_registry_scope CHECK (scope IN ('system', 'project')),
    CONSTRAINT ck_role_registry_code_not_blank CHECK (btrim(code) <> ''),
    CONSTRAINT ck_role_registry_display_name_not_blank CHECK (btrim(display_name) <> ''),
    CONSTRAINT ck_role_registry_permissions_json_object CHECK (jsonb_typeof(permissions_json) = 'object')
);

CREATE TABLE IF NOT EXISTS project_members (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    project_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    member_status TEXT NOT NULL DEFAULT 'active',
    joined_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    created_by BIGINT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    removed_at TIMESTAMPTZ,
    CONSTRAINT pk_project_members PRIMARY KEY (id),
    CONSTRAINT uq_project_members_project_user UNIQUE (project_id, user_id),
    CONSTRAINT fk_project_members_project_id_projects FOREIGN KEY (project_id) REFERENCES projects (id),
    CONSTRAINT fk_project_members_user_id_users FOREIGN KEY (user_id) REFERENCES users (id),
    CONSTRAINT fk_project_members_created_by_users FOREIGN KEY (created_by) REFERENCES users (id),
    CONSTRAINT ck_project_members_status CHECK (member_status IN ('active', 'disabled', 'invited', 'removed'))
);

CREATE INDEX IF NOT EXISTS ix_project_members_project_id
    ON project_members (project_id);

CREATE INDEX IF NOT EXISTS ix_project_members_user_id
    ON project_members (user_id);

CREATE TABLE IF NOT EXISTS member_role_bindings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    project_member_id BIGINT NOT NULL,
    role_id BIGINT NOT NULL,
    role_scope TEXT NOT NULL DEFAULT 'project',
    granted_by BIGINT,
    granted_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    revoked_by BIGINT,
    revoked_at TIMESTAMPTZ,
    status TEXT NOT NULL DEFAULT 'active',
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT pk_member_role_bindings PRIMARY KEY (id),
    CONSTRAINT fk_member_role_bindings_project_member_id_project_members FOREIGN KEY (project_member_id) REFERENCES project_members (id),
    CONSTRAINT fk_member_role_bindings_role_registry_project FOREIGN KEY (role_id, role_scope) REFERENCES role_registry (id, scope),
    CONSTRAINT fk_member_role_bindings_granted_by_users FOREIGN KEY (granted_by) REFERENCES users (id),
    CONSTRAINT fk_member_role_bindings_revoked_by_users FOREIGN KEY (revoked_by) REFERENCES users (id),
    CONSTRAINT ck_member_role_bindings_status CHECK (status IN ('active', 'revoked')),
    CONSTRAINT ck_member_role_bindings_role_scope_project CHECK (role_scope = 'project')
);

CREATE UNIQUE INDEX IF NOT EXISTS uq_member_role_bindings_active_member_role
    ON member_role_bindings (project_member_id, role_id)
    WHERE status = 'active';

CREATE INDEX IF NOT EXISTS ix_member_role_bindings_role_id
    ON member_role_bindings (role_id);

CREATE TABLE IF NOT EXISTS assets (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    public_id TEXT NOT NULL,
    asset_type TEXT NOT NULL,
    storage_path TEXT NOT NULL,
    original_filename TEXT,
    mime_type TEXT,
    size_bytes BIGINT NOT NULL,
    sha256 CHAR(64) NOT NULL,
    width INTEGER,
    height INTEGER,
    created_by BIGINT,
    readonly BOOLEAN NOT NULL DEFAULT true,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    deleted_at TIMESTAMPTZ,
    CONSTRAINT pk_assets PRIMARY KEY (id),
    CONSTRAINT uq_assets_public_id UNIQUE (public_id),
    CONSTRAINT uq_assets_sha256 UNIQUE (sha256),
    CONSTRAINT fk_assets_created_by_users FOREIGN KEY (created_by) REFERENCES users (id),
    CONSTRAINT ck_assets_size_bytes CHECK (size_bytes >= 0),
    CONSTRAINT ck_assets_width CHECK (width IS NULL OR width > 0),
    CONSTRAINT ck_assets_height CHECK (height IS NULL OR height > 0),
    CONSTRAINT ck_assets_public_id_not_blank CHECK (btrim(public_id) <> ''),
    CONSTRAINT ck_assets_asset_type_not_blank CHECK (btrim(asset_type) <> ''),
    CONSTRAINT ck_assets_storage_path_not_blank CHECK (btrim(storage_path) <> '')
);

CREATE INDEX IF NOT EXISTS ix_assets_asset_type
    ON assets (asset_type);

CREATE TABLE IF NOT EXISTS documents (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    public_id TEXT NOT NULL,
    project_id BIGINT NOT NULL,
    document_code TEXT,
    document_type TEXT NOT NULL,
    source_type TEXT,
    authorization_id BIGINT,
    domain_metadata_json JSONB NOT NULL DEFAULT '{}'::jsonb,
    split TEXT NOT NULL DEFAULT 'train',
    lock_status TEXT NOT NULL DEFAULT 'unlocked',
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT pk_documents PRIMARY KEY (id),
    CONSTRAINT uq_documents_public_id UNIQUE (public_id),
    CONSTRAINT uq_documents_id_project UNIQUE (id, project_id),
    CONSTRAINT fk_documents_project_id_projects FOREIGN KEY (project_id) REFERENCES projects (id),
    CONSTRAINT fk_documents_authorization_id_assets FOREIGN KEY (authorization_id) REFERENCES assets (id),
    CONSTRAINT ck_documents_split CHECK (split IN ('train', 'val', 'eval', 'external_auxiliary')),
    CONSTRAINT ck_documents_lock_status CHECK (lock_status IN ('unlocked', 'locked')),
    CONSTRAINT ck_documents_public_id_not_blank CHECK (btrim(public_id) <> ''),
    CONSTRAINT ck_documents_document_type_not_blank CHECK (btrim(document_type) <> ''),
    CONSTRAINT ck_documents_domain_metadata_json_object CHECK (jsonb_typeof(domain_metadata_json) = 'object')
);

CREATE UNIQUE INDEX IF NOT EXISTS uq_documents_project_document_code
    ON documents (project_id, document_code)
    WHERE document_code IS NOT NULL;

CREATE INDEX IF NOT EXISTS ix_documents_project_id
    ON documents (project_id);

CREATE INDEX IF NOT EXISTS ix_documents_split
    ON documents (split);

CREATE TABLE IF NOT EXISTS pages (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    document_id BIGINT NOT NULL,
    public_id TEXT NOT NULL,
    page_index INTEGER NOT NULL,
    image_asset_id BIGINT,
    width INTEGER NOT NULL,
    height INTEGER NOT NULL,
    capture_method TEXT,
    visual_difficulty TEXT,
    status TEXT NOT NULL DEFAULT 'imported',
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT pk_pages PRIMARY KEY (id),
    CONSTRAINT uq_pages_public_id UNIQUE (public_id),
    CONSTRAINT uq_pages_id_document UNIQUE (id, document_id),
    CONSTRAINT uq_pages_document_page_index UNIQUE (document_id, page_index),
    CONSTRAINT fk_pages_document_id_documents FOREIGN KEY (document_id) REFERENCES documents (id),
    CONSTRAINT fk_pages_image_asset_id_assets FOREIGN KEY (image_asset_id) REFERENCES assets (id),
    CONSTRAINT ck_pages_page_index CHECK (page_index >= 0),
    CONSTRAINT ck_pages_width CHECK (width > 0),
    CONSTRAINT ck_pages_height CHECK (height > 0),
    CONSTRAINT ck_pages_status CHECK (status IN ('imported', 'preannotated', 'annotated', 'reviewed', 'locked')),
    CONSTRAINT ck_pages_public_id_not_blank CHECK (btrim(public_id) <> '')
);

CREATE INDEX IF NOT EXISTS ix_pages_document_id
    ON pages (document_id);

CREATE INDEX IF NOT EXISTS ix_pages_status
    ON pages (status);

CREATE INDEX IF NOT EXISTS ix_pages_visual_difficulty
    ON pages (visual_difficulty);

CREATE TABLE IF NOT EXISTS label_registry (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    project_id BIGINT,
    namespace TEXT NOT NULL,
    name TEXT NOT NULL,
    display_name TEXT NOT NULL,
    geometry_types_json JSONB NOT NULL DEFAULT '[]'::jsonb,
    attributes_schema_json JSONB NOT NULL DEFAULT '{}'::jsonb,
    exportable_to_pp_doclayout_v3 BOOLEAN NOT NULL DEFAULT false,
    default_color TEXT,
    is_builtin BOOLEAN NOT NULL DEFAULT false,
    is_active BOOLEAN NOT NULL DEFAULT true,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT pk_label_registry PRIMARY KEY (id),
    CONSTRAINT uq_label_registry_project_namespace_name UNIQUE NULLS NOT DISTINCT (project_id, namespace, name),
    CONSTRAINT fk_label_registry_project_id_projects FOREIGN KEY (project_id) REFERENCES projects (id),
    CONSTRAINT ck_label_registry_namespace_not_blank CHECK (btrim(namespace) <> ''),
    CONSTRAINT ck_label_registry_name_not_blank CHECK (btrim(name) <> ''),
    CONSTRAINT ck_label_registry_display_name_not_blank CHECK (btrim(display_name) <> ''),
    CONSTRAINT ck_label_registry_geometry_types_json_array CHECK (jsonb_typeof(geometry_types_json) = 'array'),
    CONSTRAINT ck_label_registry_attributes_schema_json_object CHECK (jsonb_typeof(attributes_schema_json) = 'object')
);

CREATE INDEX IF NOT EXISTS ix_label_registry_project_id
    ON label_registry (project_id);

CREATE INDEX IF NOT EXISTS ix_label_registry_namespace_name
    ON label_registry (namespace, name);

CREATE TABLE IF NOT EXISTS annotation_revisions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    public_id TEXT NOT NULL,
    project_id BIGINT NOT NULL,
    document_id BIGINT NOT NULL,
    page_id BIGINT NOT NULL,
    revision_no INTEGER NOT NULL,
    parent_revision_id BIGINT,
    annotation_json_asset_id BIGINT NOT NULL,
    status TEXT NOT NULL DEFAULT 'draft',
    qc_status TEXT NOT NULL DEFAULT 'pending',
    created_by BIGINT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    change_summary TEXT,
    change_reason TEXT,
    CONSTRAINT pk_annotation_revisions PRIMARY KEY (id),
    CONSTRAINT uq_annotation_revisions_public_id UNIQUE (public_id),
    CONSTRAINT uq_annotation_revisions_page_revision_no UNIQUE (page_id, revision_no),
    CONSTRAINT uq_annotation_revisions_id_page UNIQUE (id, page_id),
    CONSTRAINT fk_annotation_revisions_project_id_projects FOREIGN KEY (project_id) REFERENCES projects (id),
    CONSTRAINT fk_annotation_revisions_document_id_documents FOREIGN KEY (document_id) REFERENCES documents (id),
    CONSTRAINT fk_annotation_revisions_page_id_pages FOREIGN KEY (page_id) REFERENCES pages (id),
    CONSTRAINT fk_annotation_revisions_document_project FOREIGN KEY (document_id, project_id) REFERENCES documents (id, project_id),
    CONSTRAINT fk_annotation_revisions_page_document FOREIGN KEY (page_id, document_id) REFERENCES pages (id, document_id),
    CONSTRAINT fk_annotation_revisions_parent_revision_id_annotation_revisions FOREIGN KEY (parent_revision_id) REFERENCES annotation_revisions (id),
    CONSTRAINT fk_annotation_revisions_parent_same_page FOREIGN KEY (parent_revision_id, page_id) REFERENCES annotation_revisions (id, page_id),
    CONSTRAINT fk_annotation_revisions_annotation_json_asset_id_assets FOREIGN KEY (annotation_json_asset_id) REFERENCES assets (id),
    CONSTRAINT fk_annotation_revisions_created_by_users FOREIGN KEY (created_by) REFERENCES users (id),
    CONSTRAINT ck_annotation_revisions_revision_no CHECK (revision_no > 0),
    CONSTRAINT ck_annotation_revisions_status CHECK (status IN ('draft', 'submitted', 'reviewed', 'locked', 'superseded')),
    CONSTRAINT ck_annotation_revisions_qc_status CHECK (qc_status IN ('pending', 'passed', 'failed', 'warning')),
    CONSTRAINT ck_annotation_revisions_public_id_not_blank CHECK (btrim(public_id) <> '')
);

CREATE INDEX IF NOT EXISTS ix_annotation_revisions_project_id
    ON annotation_revisions (project_id);

CREATE INDEX IF NOT EXISTS ix_annotation_revisions_document_id
    ON annotation_revisions (document_id);

CREATE INDEX IF NOT EXISTS ix_annotation_revisions_page_id
    ON annotation_revisions (page_id);

CREATE INDEX IF NOT EXISTS ix_annotation_revisions_page_status_revision_no
    ON annotation_revisions (page_id, status, revision_no DESC);

CREATE TABLE IF NOT EXISTS annotation_objects (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    revision_id BIGINT NOT NULL,
    ann_id TEXT NOT NULL,
    label_namespace TEXT NOT NULL,
    label_name TEXT NOT NULL,
    bbox_xyxy JSONB,
    quad JSONB,
    polygon JSONB,
    read_order INTEGER,
    attributes_json JSONB NOT NULL DEFAULT '{}'::jsonb,
    source_refs_json JSONB NOT NULL DEFAULT '[]'::jsonb,
    status TEXT NOT NULL DEFAULT 'active',
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT pk_annotation_objects PRIMARY KEY (id),
    CONSTRAINT uq_annotation_objects_revision_ann UNIQUE (revision_id, ann_id),
    CONSTRAINT fk_annotation_objects_revision_id_annotation_revisions FOREIGN KEY (revision_id) REFERENCES annotation_revisions (id) ON DELETE CASCADE,
    CONSTRAINT ck_annotation_objects_read_order CHECK (read_order IS NULL OR read_order > 0),
    CONSTRAINT ck_annotation_objects_status CHECK (status IN ('draft', 'active', 'deleted')),
    CONSTRAINT ck_annotation_objects_ann_id_not_blank CHECK (btrim(ann_id) <> ''),
    CONSTRAINT ck_annotation_objects_label_namespace_not_blank CHECK (btrim(label_namespace) <> ''),
    CONSTRAINT ck_annotation_objects_label_name_not_blank CHECK (btrim(label_name) <> ''),
    CONSTRAINT ck_annotation_objects_bbox_xyxy_json_array CHECK (bbox_xyxy IS NULL OR jsonb_typeof(bbox_xyxy) = 'array'),
    CONSTRAINT ck_annotation_objects_quad_json_array CHECK (quad IS NULL OR jsonb_typeof(quad) = 'array'),
    CONSTRAINT ck_annotation_objects_polygon_json_array CHECK (polygon IS NULL OR jsonb_typeof(polygon) = 'array'),
    CONSTRAINT ck_annotation_objects_attributes_json_object CHECK (jsonb_typeof(attributes_json) = 'object'),
    CONSTRAINT ck_annotation_objects_source_refs_json_container CHECK (jsonb_typeof(source_refs_json) IN ('object', 'array'))
);

CREATE INDEX IF NOT EXISTS ix_annotation_objects_revision_id
    ON annotation_objects (revision_id);

CREATE INDEX IF NOT EXISTS ix_annotation_objects_label
    ON annotation_objects (label_namespace, label_name);

CREATE INDEX IF NOT EXISTS ix_annotation_objects_status
    ON annotation_objects (status);

CREATE INDEX IF NOT EXISTS ix_annotation_objects_read_order
    ON annotation_objects (read_order);

CREATE TABLE IF NOT EXISTS relation_objects (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    revision_id BIGINT NOT NULL,
    rel_id TEXT NOT NULL,
    relation_type TEXT NOT NULL,
    from_ann_id TEXT NOT NULL,
    to_ann_id TEXT NOT NULL,
    attributes_json JSONB NOT NULL DEFAULT '{}'::jsonb,
    status TEXT NOT NULL DEFAULT 'active',
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT pk_relation_objects PRIMARY KEY (id),
    CONSTRAINT uq_relation_objects_revision_rel UNIQUE (revision_id, rel_id),
    CONSTRAINT fk_relation_objects_revision_id_annotation_revisions FOREIGN KEY (revision_id) REFERENCES annotation_revisions (id) ON DELETE CASCADE,
    CONSTRAINT fk_relation_objects_from_annotation_object FOREIGN KEY (revision_id, from_ann_id) REFERENCES annotation_objects (revision_id, ann_id) ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED,
    CONSTRAINT fk_relation_objects_to_annotation_object FOREIGN KEY (revision_id, to_ann_id) REFERENCES annotation_objects (revision_id, ann_id) ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED,
    CONSTRAINT ck_relation_objects_status CHECK (status IN ('active', 'deleted')),
    CONSTRAINT ck_relation_objects_rel_id_not_blank CHECK (btrim(rel_id) <> ''),
    CONSTRAINT ck_relation_objects_relation_type_not_blank CHECK (btrim(relation_type) <> ''),
    CONSTRAINT ck_relation_objects_from_ann_id_not_blank CHECK (btrim(from_ann_id) <> ''),
    CONSTRAINT ck_relation_objects_to_ann_id_not_blank CHECK (btrim(to_ann_id) <> ''),
    CONSTRAINT ck_relation_objects_distinct_ann CHECK (from_ann_id <> to_ann_id),
    CONSTRAINT ck_relation_objects_attributes_json_object CHECK (jsonb_typeof(attributes_json) = 'object')
);

CREATE INDEX IF NOT EXISTS ix_relation_objects_revision_id
    ON relation_objects (revision_id);

CREATE INDEX IF NOT EXISTS ix_relation_objects_relation_type
    ON relation_objects (relation_type);

CREATE TABLE IF NOT EXISTS background_jobs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    public_id TEXT NOT NULL,
    job_type TEXT NOT NULL,
    status TEXT NOT NULL DEFAULT 'queued',
    payload_json JSONB NOT NULL DEFAULT '{}'::jsonb,
    result_json JSONB NOT NULL DEFAULT '{}'::jsonb,
    progress NUMERIC(5,2) NOT NULL DEFAULT 0,
    created_by BIGINT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    started_at TIMESTAMPTZ,
    finished_at TIMESTAMPTZ,
    error_message TEXT,
    CONSTRAINT pk_background_jobs PRIMARY KEY (id),
    CONSTRAINT uq_background_jobs_public_id UNIQUE (public_id),
    CONSTRAINT fk_background_jobs_created_by_users FOREIGN KEY (created_by) REFERENCES users (id),
    CONSTRAINT ck_background_jobs_status CHECK (status IN ('queued', 'running', 'succeeded', 'failed', 'canceled')),
    CONSTRAINT ck_background_jobs_progress CHECK (progress >= 0 AND progress <= 100),
    CONSTRAINT ck_background_jobs_public_id_not_blank CHECK (btrim(public_id) <> ''),
    CONSTRAINT ck_background_jobs_job_type_not_blank CHECK (btrim(job_type) <> ''),
    CONSTRAINT ck_background_jobs_payload_json_object CHECK (jsonb_typeof(payload_json) = 'object'),
    CONSTRAINT ck_background_jobs_result_json_object CHECK (jsonb_typeof(result_json) = 'object')
);

CREATE INDEX IF NOT EXISTS ix_background_jobs_job_type
    ON background_jobs (job_type);

CREATE INDEX IF NOT EXISTS ix_background_jobs_status
    ON background_jobs (status);

CREATE TABLE IF NOT EXISTS qc_results (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    project_id BIGINT NOT NULL,
    document_id BIGINT,
    page_id BIGINT,
    revision_id BIGINT,
    qc_type TEXT NOT NULL,
    status TEXT NOT NULL,
    summary TEXT,
    details_json JSONB NOT NULL DEFAULT '{}'::jsonb,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    created_by_job_id BIGINT,
    CONSTRAINT pk_qc_results PRIMARY KEY (id),
    CONSTRAINT fk_qc_results_project_id_projects FOREIGN KEY (project_id) REFERENCES projects (id),
    CONSTRAINT fk_qc_results_document_id_documents FOREIGN KEY (document_id) REFERENCES documents (id),
    CONSTRAINT fk_qc_results_page_id_pages FOREIGN KEY (page_id) REFERENCES pages (id),
    CONSTRAINT fk_qc_results_revision_id_annotation_revisions FOREIGN KEY (revision_id) REFERENCES annotation_revisions (id),
    CONSTRAINT fk_qc_results_document_project FOREIGN KEY (document_id, project_id) REFERENCES documents (id, project_id),
    CONSTRAINT fk_qc_results_page_document FOREIGN KEY (page_id, document_id) REFERENCES pages (id, document_id),
    CONSTRAINT fk_qc_results_revision_page FOREIGN KEY (revision_id, page_id) REFERENCES annotation_revisions (id, page_id),
    CONSTRAINT fk_qc_results_created_by_job_id_background_jobs FOREIGN KEY (created_by_job_id) REFERENCES background_jobs (id),
    CONSTRAINT ck_qc_results_qc_type CHECK (qc_type IN ('schema', 'geometry', 'k12_structure', 'dataset', 'export')),
    CONSTRAINT ck_qc_results_status CHECK (status IN ('passed', 'warning', 'failed')),
    CONSTRAINT ck_qc_results_page_requires_document CHECK (page_id IS NULL OR document_id IS NOT NULL),
    CONSTRAINT ck_qc_results_revision_requires_page CHECK (revision_id IS NULL OR page_id IS NOT NULL),
    CONSTRAINT ck_qc_results_details_json_object CHECK (jsonb_typeof(details_json) = 'object')
);

CREATE INDEX IF NOT EXISTS ix_qc_results_project_id
    ON qc_results (project_id);

CREATE INDEX IF NOT EXISTS ix_qc_results_revision_id
    ON qc_results (revision_id);

CREATE INDEX IF NOT EXISTS ix_qc_results_status
    ON qc_results (status);

CREATE TABLE IF NOT EXISTS export_jobs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    project_id BIGINT NOT NULL,
    public_id TEXT NOT NULL,
    export_type TEXT NOT NULL,
    export_profile_json JSONB NOT NULL DEFAULT '{}'::jsonb,
    input_scope_json JSONB NOT NULL DEFAULT '{}'::jsonb,
    source_revisions_json JSONB NOT NULL DEFAULT '[]'::jsonb,
    status TEXT NOT NULL DEFAULT 'queued',
    output_dir TEXT,
    report_asset_id BIGINT,
    created_by BIGINT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    started_at TIMESTAMPTZ,
    finished_at TIMESTAMPTZ,
    error_message TEXT,
    CONSTRAINT pk_export_jobs PRIMARY KEY (id),
    CONSTRAINT uq_export_jobs_public_id UNIQUE (public_id),
    CONSTRAINT fk_export_jobs_project_id_projects FOREIGN KEY (project_id) REFERENCES projects (id),
    CONSTRAINT fk_export_jobs_report_asset_id_assets FOREIGN KEY (report_asset_id) REFERENCES assets (id),
    CONSTRAINT fk_export_jobs_created_by_users FOREIGN KEY (created_by) REFERENCES users (id),
    CONSTRAINT ck_export_jobs_status CHECK (status IN ('queued', 'running', 'succeeded', 'failed', 'canceled')),
    CONSTRAINT ck_export_jobs_public_id_not_blank CHECK (btrim(public_id) <> ''),
    CONSTRAINT ck_export_jobs_export_type_not_blank CHECK (btrim(export_type) <> ''),
    CONSTRAINT ck_export_jobs_export_profile_json_object CHECK (jsonb_typeof(export_profile_json) = 'object'),
    CONSTRAINT ck_export_jobs_input_scope_json_object CHECK (jsonb_typeof(input_scope_json) = 'object'),
    CONSTRAINT ck_export_jobs_source_revisions_json_array CHECK (jsonb_typeof(source_revisions_json) = 'array')
);

CREATE INDEX IF NOT EXISTS ix_export_jobs_project_id
    ON export_jobs (project_id);

CREATE INDEX IF NOT EXISTS ix_export_jobs_status
    ON export_jobs (status);

CREATE TABLE IF NOT EXISTS audit_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    project_id BIGINT,
    actor_id BIGINT,
    action TEXT NOT NULL,
    resource_type TEXT NOT NULL,
    resource_id TEXT,
    before_json JSONB,
    after_json JSONB,
    request_id TEXT,
    ip_address INET,
    user_agent TEXT,
    prev_hash CHAR(64),
    entry_hash CHAR(64),
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT pk_audit_logs PRIMARY KEY (id),
    CONSTRAINT fk_audit_logs_project_id_projects FOREIGN KEY (project_id) REFERENCES projects (id),
    CONSTRAINT fk_audit_logs_actor_id_users FOREIGN KEY (actor_id) REFERENCES users (id),
    CONSTRAINT ck_audit_logs_action_not_blank CHECK (btrim(action) <> ''),
    CONSTRAINT ck_audit_logs_resource_type_not_blank CHECK (btrim(resource_type) <> ''),
    CONSTRAINT ck_audit_logs_before_json_object CHECK (before_json IS NULL OR jsonb_typeof(before_json) = 'object'),
    CONSTRAINT ck_audit_logs_after_json_object CHECK (after_json IS NULL OR jsonb_typeof(after_json) = 'object')
);

CREATE INDEX IF NOT EXISTS ix_audit_logs_project_id
    ON audit_logs (project_id);

CREATE INDEX IF NOT EXISTS ix_audit_logs_actor_id
    ON audit_logs (actor_id);

CREATE INDEX IF NOT EXISTS ix_audit_logs_resource
    ON audit_logs (resource_type, resource_id);

CREATE INDEX IF NOT EXISTS ix_audit_logs_created_at
    ON audit_logs (created_at);

INSERT INTO role_registry (code, display_name, scope, description, permissions_json, is_builtin, is_active)
VALUES
    (
        'system_admin',
        '系统管理员',
        'system',
        '平台系统级管理角色，不绑定到项目成员。',
        jsonb_build_object(
            'capabilities',
            ARRAY[
                'can_manage_system_users',
                'can_view_audit_log'
            ]
        ),
        true,
        true
    ),
    (
        'viewer',
        '只读查看者',
        'project',
        '可查看项目、文档、页面和标注结果。',
        jsonb_build_object(
            'capabilities',
            ARRAY[
                'can_view_project'
            ]
        ),
        true,
        true
    ),
    (
        'annotator',
        '标注员',
        'project',
        '可创建和编辑草稿标注版本。',
        jsonb_build_object(
            'capabilities',
            ARRAY[
                'can_view_project',
                'can_create_annotation_revision',
                'can_submit_revision'
            ]
        ),
        true,
        true
    ),
    (
        'reviewer',
        '复核员',
        'project',
        '可查看和复核标注版本。',
        jsonb_build_object(
            'capabilities',
            ARRAY[
                'can_view_project',
                'can_review_revision'
            ]
        ),
        true,
        true
    ),
    (
        'data_manager',
        '数据管理员',
        'project',
        '可导入资产、管理文档和页面。',
        jsonb_build_object(
            'capabilities',
            ARRAY[
                'can_view_project',
                'can_upload_assets',
                'can_import_pages'
            ]
        ),
        true,
        true
    ),
    (
        'exporter',
        '导出员',
        'project',
        '可创建导出任务和下载导出产物。',
        jsonb_build_object(
            'capabilities',
            ARRAY[
                'can_view_project',
                'can_create_export_job',
                'can_download_export'
            ]
        ),
        true,
        true
    ),
    (
        'project_admin',
        '项目管理员',
        'project',
        '可管理项目成员、标签、关系、锁定、回滚和项目导出。',
        jsonb_build_object(
            'capabilities',
            ARRAY[
                'can_view_project',
                'can_upload_assets',
                'can_import_pages',
                'can_create_annotation_revision',
                'can_submit_revision',
                'can_review_revision',
                'can_manage_labels',
                'can_manage_relations',
                'can_manage_project_members',
                'can_create_export_job',
                'can_download_export',
                'can_lock_revision',
                'can_unlock_revision',
                'can_rollback_revision',
                'can_view_audit_log'
            ]
        ),
        true,
        true
    )
ON CONFLICT (code) DO UPDATE SET
    display_name = EXCLUDED.display_name,
    scope = EXCLUDED.scope,
    description = EXCLUDED.description,
    permissions_json = EXCLUDED.permissions_json,
    is_builtin = true,
    is_active = true,
    updated_at = now();

COMMENT ON TABLE projects IS '项目表：保存标注项目的基础信息和 schema 版本。';
COMMENT ON COLUMN projects.id IS '内部主键：BIGINT identity，仅用于数据库关联。';
COMMENT ON COLUMN projects.schema_version IS '项目 schema 版本：用于后续数据格式升级和兼容判断。';

COMMENT ON TABLE users IS '用户表：保存平台账号，是审计、创建人、复核人和权限校验的基础事实来源。';
COMMENT ON COLUMN users.password_hash IS '密码哈希：不得明文保存，不得返回前端。';
COMMENT ON COLUMN users.status IS '用户状态：active 可用，disabled 禁用，pending 待初始化。';
COMMENT ON COLUMN users.is_system_admin IS '系统管理员标记：只用于系统级初始化和维护，不替代项目角色。';

COMMENT ON TABLE role_registry IS '角色注册表：保存系统内置角色和权限 JSON，是 capability 计算来源之一。';
COMMENT ON COLUMN role_registry.code IS '角色编码：viewer / annotator / reviewer / data_manager / exporter / project_admin / system_admin。';
COMMENT ON COLUMN role_registry.scope IS '角色作用域：system 表示系统级角色，project 表示项目成员可绑定角色。';
COMMENT ON COLUMN role_registry.permissions_json IS '权限 JSON：后端 capability 计算使用，前端只消费计算结果。';

COMMENT ON TABLE project_members IS '项目成员表：保存用户和项目的成员关系。';
COMMENT ON COLUMN project_members.member_status IS '成员状态：active / disabled / invited / removed。';
COMMENT ON COLUMN project_members.created_by IS '创建人：引用 users.id，保留成员加入来源。';

COMMENT ON TABLE member_role_bindings IS '成员角色绑定表：保存项目成员与项目级角色的授权和撤销记录。';
COMMENT ON COLUMN member_role_bindings.role_scope IS '角色作用域冗余列：固定为 project，用于数据库层禁止绑定系统级角色。';
COMMENT ON COLUMN member_role_bindings.status IS '绑定状态：active 表示当前有效，revoked 表示已撤销。';

COMMENT ON TABLE assets IS '文件资产表：保存原始文件、页面图像、标注 JSON、导出文件等文件级元数据。';
COMMENT ON COLUMN assets.public_id IS '公开资产编号：用于 API、manifest 和文件追踪，不作为数据库外键主键。';
COMMENT ON COLUMN assets.storage_path IS '受控存储相对路径：不得直接来自前端任意路径。';
COMMENT ON COLUMN assets.sha256 IS '文件 SHA-256：用于完整性校验和防覆盖。';
COMMENT ON COLUMN assets.readonly IS '只读标记：原始资产、模型输出和历史 revision 默认只追加不覆盖。';

COMMENT ON TABLE documents IS '文档表：保存原始试卷、PDF 或其他文档级元数据。';
COMMENT ON COLUMN documents.public_id IS '公开文档编号：用于 API、manifest 和审计展示。';
COMMENT ON COLUMN documents.domain_metadata_json IS '场景扩展元数据：K12 学科、年级、考试类型等放这里，不写死在核心字段。';
COMMENT ON COLUMN documents.split IS '数据集划分：train / val / eval / external_auxiliary。';

COMMENT ON TABLE pages IS '页面表：保存文档页和页面图像的关系。';
COMMENT ON COLUMN pages.id IS '页面内部主键：仅用于数据库关联。';
COMMENT ON COLUMN pages.public_id IS '公开稳定页面编号：前端路由、API path 和审计展示使用。';
COMMENT ON COLUMN pages.document_id IS '文档内部主键：引用 documents.id。';

COMMENT ON TABLE label_registry IS '标签注册表：保存官方 layout 标签和场景扩展标签。';
COMMENT ON COLUMN label_registry.project_id IS '所属项目：为空表示全局内置标签。';
COMMENT ON COLUMN label_registry.geometry_types_json IS '允许的几何类型列表，例如 bbox_xyxy / quad / polygon。';
COMMENT ON COLUMN label_registry.attributes_schema_json IS '标签属性 schema：用于后续 schema QC。';

COMMENT ON TABLE annotation_revisions IS '标注版本表：保存每次页面标注提交形成的不可变版本记录。';
COMMENT ON COLUMN annotation_revisions.public_id IS '公开标注版本编号：用于 API、manifest、导出追踪和审计展示。';
COMMENT ON COLUMN annotation_revisions.page_id IS '页面内部主键：引用 pages.id；公开页面编号位于 pages.public_id。';
COMMENT ON COLUMN annotation_revisions.revision_no IS '标注版本号：同一页面内递增，回滚也创建新版本。';
COMMENT ON COLUMN annotation_revisions.annotation_json_asset_id IS '标注 JSON 资产：引用 assets.id，完整标注事实保存在文件系统。';

COMMENT ON TABLE annotation_objects IS '标注对象索引表：从 annotation revision JSON 抽取，用于查询和导出前索引。';
COMMENT ON COLUMN annotation_objects.ann_id IS '标注对象编号：来自 revision JSON，同一 revision 内唯一。';
COMMENT ON COLUMN annotation_objects.read_order IS '阅读顺序索引：事实来源仍是 revision JSON。';

COMMENT ON TABLE relation_objects IS '关系对象索引表：从 annotation revision JSON 抽取的对象关系索引。';
COMMENT ON COLUMN relation_objects.rel_id IS '关系编号：来自 revision JSON，同一 revision 内唯一。';
COMMENT ON COLUMN relation_objects.from_ann_id IS '关系起点对象编号：必须存在于同一 revision 的 annotation_objects。';
COMMENT ON COLUMN relation_objects.to_ann_id IS '关系终点对象编号：必须存在于同一 revision 的 annotation_objects。';

COMMENT ON TABLE background_jobs IS '后台任务表：保存长任务状态和结果摘要；Redis 只作为队列，不保存业务事实。';
COMMENT ON COLUMN background_jobs.public_id IS '公开任务编号：用于 API 查询和任务 artifact 路径。';
COMMENT ON COLUMN background_jobs.progress IS '任务进度：0 到 100。';

COMMENT ON TABLE qc_results IS '质检结果表：保存 schema、geometry、dataset、export 等 QC 结果。';
COMMENT ON COLUMN qc_results.page_id IS '页面内部主键：引用 pages.id；公开页面编号位于 pages.public_id。';
COMMENT ON COLUMN qc_results.details_json IS '质检详情 JSON：保存 errors / warnings 等结构化明细。';

COMMENT ON TABLE export_jobs IS '导出任务表：保存导出请求、状态、范围、输出路径和报告资产。';
COMMENT ON COLUMN export_jobs.public_id IS '公开导出编号：用于 API、manifest 和 artifact 路径。';
COMMENT ON COLUMN export_jobs.source_revisions_json IS '来源 revision 列表：用于导出包可追溯。';

COMMENT ON TABLE audit_logs IS '审计日志表：保存角色变更、成员管理、锁定、回滚、导出和下载等关键操作。';
COMMENT ON COLUMN audit_logs.resource_id IS '资源编号：优先记录对外展示的公开编号，内部排查场景可记录带前缀的内部编号。';
COMMENT ON COLUMN audit_logs.prev_hash IS '上一条审计哈希：后续用于审计日志哈希链。';
COMMENT ON COLUMN audit_logs.entry_hash IS '当前审计哈希：后续用于审计日志哈希链。';

DROP TRIGGER IF EXISTS trg_projects_set_updated_at ON projects;
CREATE TRIGGER trg_projects_set_updated_at
    BEFORE UPDATE ON projects
    FOR EACH ROW
    EXECUTE FUNCTION set_updated_at();

DROP TRIGGER IF EXISTS trg_users_set_updated_at ON users;
CREATE TRIGGER trg_users_set_updated_at
    BEFORE UPDATE ON users
    FOR EACH ROW
    EXECUTE FUNCTION set_updated_at();

DROP TRIGGER IF EXISTS trg_role_registry_set_updated_at ON role_registry;
CREATE TRIGGER trg_role_registry_set_updated_at
    BEFORE UPDATE ON role_registry
    FOR EACH ROW
    EXECUTE FUNCTION set_updated_at();

DROP TRIGGER IF EXISTS trg_project_members_set_updated_at ON project_members;
CREATE TRIGGER trg_project_members_set_updated_at
    BEFORE UPDATE ON project_members
    FOR EACH ROW
    EXECUTE FUNCTION set_updated_at();

DROP TRIGGER IF EXISTS trg_member_role_bindings_set_updated_at ON member_role_bindings;
CREATE TRIGGER trg_member_role_bindings_set_updated_at
    BEFORE UPDATE ON member_role_bindings
    FOR EACH ROW
    EXECUTE FUNCTION set_updated_at();

DROP TRIGGER IF EXISTS trg_assets_set_updated_at ON assets;
CREATE TRIGGER trg_assets_set_updated_at
    BEFORE UPDATE ON assets
    FOR EACH ROW
    EXECUTE FUNCTION set_updated_at();

DROP TRIGGER IF EXISTS trg_documents_set_updated_at ON documents;
CREATE TRIGGER trg_documents_set_updated_at
    BEFORE UPDATE ON documents
    FOR EACH ROW
    EXECUTE FUNCTION set_updated_at();

DROP TRIGGER IF EXISTS trg_pages_set_updated_at ON pages;
CREATE TRIGGER trg_pages_set_updated_at
    BEFORE UPDATE ON pages
    FOR EACH ROW
    EXECUTE FUNCTION set_updated_at();

DROP TRIGGER IF EXISTS trg_label_registry_set_updated_at ON label_registry;
CREATE TRIGGER trg_label_registry_set_updated_at
    BEFORE UPDATE ON label_registry
    FOR EACH ROW
    EXECUTE FUNCTION set_updated_at();

DROP TRIGGER IF EXISTS trg_annotation_revisions_set_updated_at ON annotation_revisions;
CREATE TRIGGER trg_annotation_revisions_set_updated_at
    BEFORE UPDATE ON annotation_revisions
    FOR EACH ROW
    EXECUTE FUNCTION set_updated_at();

DROP TRIGGER IF EXISTS trg_annotation_objects_set_updated_at ON annotation_objects;
CREATE TRIGGER trg_annotation_objects_set_updated_at
    BEFORE UPDATE ON annotation_objects
    FOR EACH ROW
    EXECUTE FUNCTION set_updated_at();

DROP TRIGGER IF EXISTS trg_relation_objects_set_updated_at ON relation_objects;
CREATE TRIGGER trg_relation_objects_set_updated_at
    BEFORE UPDATE ON relation_objects
    FOR EACH ROW
    EXECUTE FUNCTION set_updated_at();

DROP TRIGGER IF EXISTS trg_background_jobs_set_updated_at ON background_jobs;
CREATE TRIGGER trg_background_jobs_set_updated_at
    BEFORE UPDATE ON background_jobs
    FOR EACH ROW
    EXECUTE FUNCTION set_updated_at();

DROP TRIGGER IF EXISTS trg_qc_results_set_updated_at ON qc_results;
CREATE TRIGGER trg_qc_results_set_updated_at
    BEFORE UPDATE ON qc_results
    FOR EACH ROW
    EXECUTE FUNCTION set_updated_at();

DROP TRIGGER IF EXISTS trg_export_jobs_set_updated_at ON export_jobs;
CREATE TRIGGER trg_export_jobs_set_updated_at
    BEFORE UPDATE ON export_jobs
    FOR EACH ROW
    EXECUTE FUNCTION set_updated_at();

DROP TRIGGER IF EXISTS trg_audit_logs_prevent_mutation ON audit_logs;
CREATE TRIGGER trg_audit_logs_prevent_mutation
    BEFORE UPDATE OR DELETE ON audit_logs
    FOR EACH ROW
    EXECUTE FUNCTION prevent_audit_logs_mutation();
